### ISSUE TITLE
GPL3

### ISSUE THREAD

**Issue by neodave** [apraka16/swipeableOnboardingUIPageView#4]
I found this through your article, and love the implementation. I am working on a commercial project that will be open sourced itself, but under GPL2. So we can't use this due to the GPL3. Licensing can be confusing, and unless you are really sure of why you want the GPL3 you might want to consider a different license. I don't mean to be disrespectful of you choice. But as someone who has worked in open source for a long time I thought I would point this out. 

It's a beautiful solution btw...

**Comment by apraka16** [comment]
I understand. TBH, it was supposed to be free to use. I will make the license changes, and then drop a text. Thanks for informing.

**Comment by apraka16** [comment]
Thanks for the heads-up there. Have added the MIT one. Please go ahead and use the code or parts thereof, as much as you want. It's good to find out it is helpful to someone. I will close the issue now.
